### ISSUE TITLE
how to launch test?

### ISSUE THREAD

**Issue by voa18105** [rosinality/style-based-gan-pytorch#1]
Hello!
I've managed to launch train, but whats next? How to test it after? I would like to reproduce experiments with style transfer, but I do not see how to provide 2 images to generator

**Comment by rosinality** [comment]
Actually style based gan have no architectures like encoder to put images in. I think authors did style mixing by mixing the latent codes. Maybe you need to modify codes to you can inject different style latent codes at the different parts of the generator. (Also it will be better to use mixing regularization - currently not implemented yet.)
