### ISSUE TITLE
Convert weight from official repositories.

### ISSUE THREAD

**Issue by BenfenYU** [rosinality/style-based-gan-pytorch#105]
Hi
Have you tried to convert weight from official repositories for stylegan v1?
I tried it and I find there is a bias lost in your implementation, however, after I transform all weights from official repository I just got very bad results. If you have tried, may I ask for some instruction ? 3q so much.
![image](https://user-images.githubusercontent.com/33017944/94426356-0b4ee300-01c0-11eb-9aaf-54eabfbd80b2.png)

**Comment by rosinality** [comment]
I haven't tried to convert checkpoints. Anyway if you want to try it, you will need to check the output is same for each layers with converted weights.

**Comment by BenfenYU** [comment]
ok~thank you!
