### ISSUE TITLE
Saturation artifacts with large batch sizes

### ISSUE THREAD

**Issue by mileslefttogo** [rosinality/style-based-gan-pytorch#12]
Hey! Thanks a bunch for making this great implementation. I noticed that when I tune the batch sizes to be closer to Tero's numbers for 1 GPU, my training falls apart after transitioning resolutions. This doesn't seem to happen at a batch size of 16. 

Looks like this (batch size is 64 for all of these):

(Right before transition from 8x8 to 16x16)
![image](https://user-images.githubusercontent.com/17791159/54566294-ab9e3780-498d-11e9-8850-08022722e9cf.png)

(Right after transition)
![image](https://user-images.githubusercontent.com/17791159/54566319-bd7fda80-498d-11e9-88ed-80507db99ac2.png)

(A few hundred after transition)
![image](https://user-images.githubusercontent.com/17791159/54566336-ccff2380-498d-11e9-92c5-20ae60f10b9a.png)

(1500 iterations after transition)
![image](https://user-images.githubusercontent.com/17791159/54566350-d8eae580-498d-11e9-8c79-092aaccadb5e.png)

(2000 after)
![image](https://user-images.githubusercontent.com/17791159/54566371-e607d480-498d-11e9-9bd1-8c004d6419ed.png)

From here it just keeps collapsing. Did you notice this with your training at all? It doesn't seem to happen to me in Tero's tensorflow implementation with equivalent iterations

**Comment by rosinality** [comment]
I think official implementation determines transitioning iterations/phases using the total number of images used for training. My implementation uses fixed number of iterations for this, so it is not dependent of batch sizes. (sorry!) I think this can be problematic. As batch size is 4x, maybe it is better to use small number of iterations for transitioning.

Model itself is (almost) not dependent on batch sizes. One exception is mini batch discrimination, but I think this will not cause that much problems.
