### ISSUE TITLE
generate new images from checkpoints

### ISSUE THREAD

**Issue by inbalaha** [rosinality/style-based-gan-pytorch#122]
Hi, we trained the model with our data and got good samples. Now we are trying to generate new images by using our checkpoint, with the following command "python generate.py checkpoint/train_step-4.model" . 
we get this result: 
![image](https://user-images.githubusercontent.com/74650094/117108534-01134980-ad8c-11eb-85ed-a6830ad4610d.png)

the images from the samples lookes like this :
![image](https://user-images.githubusercontent.com/74650094/117108345-b560a000-ad8b-11eb-8d5a-78a768f7343e.png)
it seems like the generated image is a combination of the samples and a random style. 
is there a way to generate the image without the style? 
thanks in advance

**Comment by rosinality** [comment]
You need to set `--size` argument to the generate.py that matches with the resolutions model trained with.

**Comment by inbalaha** [comment]
thank you, it works!
