### ISSUE TITLE
Question on projecting generated images back to latent space

### ISSUE THREAD

**Issue by vinayakarannil** [rosinality/style-based-gan-pytorch#125]
Is there a way we can project back the images to get the latent vectors just like it is available in StyleGan2 repo?

**Comment by rosinality** [comment]
I think it is possible to do it with similar way to stylegan2.

**Comment by vinayakarannil** [comment]
Done! I have raised a [PR]( https://github.com/rosinality/style-based-gan-pytorch/pull/127) for the same. You may verify and merge.
