### ISSUE TITLE
Checkpoint files for new versions

### ISSUE THREAD

**Issue by PgLoLo** [rosinality/style-based-gan-pytorch#13]
In the repo issue [discussions](https://github.com/rosinality/style-based-gan-pytorch/issues/3), I found model checkpoint for the previous version of this repo, which seems noncompatible with the current version of gan. Is there any chance to get the newly trained models especially in the light of new high-quality results on FFHQ?

Or maybe I am just doing something wrong and the old checkpoint is still usable?

**Comment by rosinality** [comment]
Old weight is not compatible as I changed model at 24896bb. You can use https://drive.google.com/open?id=1TVdUGOcMRVTVaxLhmh2qVmPgWIlwE0if (trained using FFHQ, 140k iter, 256px)

**Comment by PgLoLo** [comment]
@rosinality thank you very much!
