### ISSUE TITLE
Did you update your pretrain model weight??

### ISSUE THREAD

**Issue by Johnson-yue** [rosinality/style-based-gan-pytorch#15]
Hi, I look issue #3  and have found  generator and discriminator weight. But maybe it is not a pair.

Can you give me  the same pixel-resolution and same dataset the weight of generator and discriminator?

**Comment by rosinality** [comment]
It is paired checkpoints. Do you mean running average of generator? It is not paired but I think you can make it using generator/discriminator checkpoints as it is running average of generator weights during training.

**Comment by Johnson-yue** [comment]
how much size of input image for this generator/discirminator checkpoint  ?

**Comment by rosinality** [comment]
Input image size is 256 pixels.

**Comment by Johnson-yue** [comment]
Thank you , I will finetune g and d  on my datasets .

**Comment by Johnson-yue** [comment]
@rosinality  which config should I use? ** for celebA** or ** for FFHQ** with pretrained weight

**Comment by rosinality** [comment]
You should use FFHQ.

**Comment by Johnson-yue** [comment]
reply so quickly!!!  thanks a lot!!

**Comment by Johnson-yue** [comment]
@rosinality the code default "max_size" is 1024, default "init_size" is 8.
If I train in my dataset that. input image size is 256^2,  and I want to generate size is also 256^2
, should I change **max_size** to 256 and **init_size** to 4 ?

**Comment by rosinality** [comment]
You only need to change max_size if you need to reduce final image sizes.

**Comment by Johnson-yue** [comment]
ok, 🙏 thanks
