### ISSUE TITLE
how to control the style what we want to generate?

### ISSUE THREAD

**Issue by Johnson-yue** [rosinality/style-based-gan-pytorch#17]
Hi,  I look the train.py code and I think the tensor of **label** was not used anywhere!

If I want to generate like [this image](https://github.com/rosinality/style-based-gan-pytorch/blob/master/doc/sample_mixing_ffhq.png)  , how to write this code ?

the generator input is only **gen_in1** or **gen_in2** So, how to control the style that I want to generator?

**Comment by rosinality** [comment]
You can refer to generate.py. Basically it works by using 2 latent codes, one as source images and the another one as style images.

**Comment by Johnson-yue** [comment]
ok， thank you
