### ISSUE TITLE
64 image-size

### ISSUE THREAD

**Issue by KaiwenZha** [rosinality/style-based-gan-pytorch#19]
Hello,

Where do I need to modify if the image size of my dataset is 64x64? I'm afraid I may miss some places. Thanks!

**Comment by rosinality** [comment]
You can use --max_size argument.

**Comment by KaiwenZha** [comment]
Appreciate it.

**Comment by KaiwenZha** [comment]
BTW, do I need to modify the architecture in model.py? It seems that the program will report errors in the network structure if I only modify the --max_size argument. @rosinality

**Comment by KaiwenZha** [comment]
Sorry, I've fixed it. @rosinality
