### ISSUE TITLE
gpu requirements

### ISSUE THREAD

**Issue by voa18105** [rosinality/style-based-gan-pytorch#2]
What is your graphic card? I am reaching 67% train and then it falls, saying 'CUDA out of memory'

**Comment by rosinality** [comment]
I have used P40 with 24G ram. Maybe it is better to use more gpus with dataparallel.

**Comment by voa18105** [comment]
I have 2 TITAN X with 12G, but use only 1... is there a simple way to insert data parallelization?

**Comment by voa18105** [comment]
ho, I see you already used nn.DataParallel... Does that mean that if I will write CUDA_VISIBLE_DEVICES=0,1 python3.6 train.py -d celeba ... it will automatically use both?

**Comment by rosinality** [comment]
Yes, it will use both gpus.

**Comment by voa18105** [comment]
Thank you! I will notify in 1-2 days if I managed to overcome this issue.

**Comment by RameenAbdal** [comment]
Hi, Did you manage to run the code on multiple gpus?

**Comment by voa18105** [comment]
@RameenAbdal hi, yes, it works fine. I guess it is much slower than with P40, but it does not fall
