### ISSUE TITLE
Question regarding the difference in fade in with the official implementation

### ISSUE THREAD

**Issue by yongxinw** [rosinality/style-based-gan-pytorch#23]
As stated in the original ProGAN paper, it seems that they first stabilize the resolution at i.e. 4x4 for 800000 images, and then fade in the 8x8 for another 800000. This goes on and on. In the current implementation, it seems that fade in is happening even at the stabilizing stage. Is this correct?

PS. please refer to ProGAN paper Appendix A.1

**Comment by rosinality** [comment]
This implementation also alternates fade in and stabilizing stages.

**Comment by yongxinw** [comment]
Ah I see. You took the min of 1 and the weight. Closing this now.

**Comment by yongxinw** [comment]
On a second thought, in the ProGAN paper, it seems that they are doing stabilizing and then fading in. Here since we have `alpha = min(1, 1 / args.phase * (used_sample + 1))` and `used_sample` grows from 0 up, wouldn't it reverse the order (i.e. fade in first and then stabilize) ? I think this kind of makes a difference at the very first level of resolution. Thanks!

**Comment by rosinality** [comment]
Yes, it's different. But after initial resolution it will be same.

**Comment by yongxinw** [comment]
Thanks! If I understand correctly, we start at 8x8, and at this time we fade in with the 4x4 right? My concern is that since the 4x4 is not yet learned (as we started from 8x8), would the fade-in at this stage be advantageous at all?

**Comment by rosinality** [comment]
I think it is not very meaningful. It is just the side effect of changing initial size 4x4 to 8x8.
