### ISSUE TITLE
Error on string operation on train.py

### ISSUE THREAD

**Issue by nobodykid** [rosinality/style-based-gan-pytorch#25]
Hello,

I'm trying to run your code as per your instruction on README. But I got stuck on many string operation on `train.py` such as
```
torch.save(
                {
                    'generator': generator.module.state_dict(),
                    'discriminator': discriminator.module.state_dict(),
                    'g_optimizer': g_optimizer.state_dict(),
                    'd_optimizer': d_optimizer.state_dict(),
                },
                f'checkpoint/train_step-{step}.model', <-- here
            )
```

What type of string operation did you use? Or is it different Python version? I'm using Python 3.5

**Comment by rosinality** [comment]
It is f-string of Python 3.6. You can replace it with format() if you need to run it with Python 3.5

**Comment by nobodykid** [comment]
Aaah I see, thank you very much

Is there any other major modification I should do to match with my Python 3.5 other than the string operation?

**Comment by rosinality** [comment]
https://github.com/rosinality/style-based-gan-pytorch/blob/master/train.py#L263 Underscores in the number in this line.

**Comment by nobodykid** [comment]
Gotcha. Thank you for the help
