### ISSUE TITLE
[-1, 1] normalization on fake_image?

### ISSUE THREAD

**Issue by 1Konny** [rosinality/style-based-gan-pytorch#30]
Hi, thanks for this great repo and I have a question on a small detail.

This can be minor but I found that each pixel value of real_image is normalized to the dynamic range of [-1, 1] while fake_image is not. Also, I couldn't find any operations for handling this(e.g. F.tanh or nn.Tanh). And I wonder if this is what you intended.

**Comment by rosinality** [comment]
Yes, progressive gans and style gans don't use squashing (like tanh) or clipping operations. It seems like that it is not very problematic.

**Comment by 1Konny** [comment]
Thanks for the clarification! closing this issue.
