### ISSUE TITLE
Discriminator missing an activation function after the first convolutional layer

### ISSUE THREAD

**Issue by adambielski** [rosinality/style-based-gan-pytorch#33]
After from_rgb layer in the discriminator, there is no activation function. A leaky relu nonlinearity should be applied there.

https://github.com/rosinality/style-based-gan-pytorch/blob/e5caa16e9edcb1a4ddb22206511f9339ead78ad7/model.py#L552

**Comment by rosinality** [comment]
Thank you, I missed it. I will update repo.

**Comment by rosinality** [comment]
Added this as an option at b160dbc94edc6e7f0f825bdb236d13952c8fec1a for checkpoint compatibility. I will update checkpoint later.
