### ISSUE TITLE
Possibly wrong R1 penalty

### ISSUE THREAD

**Issue by TropComplique** [rosinality/style-based-gan-pytorch#34]
Hi.
Why do you use `softplus` before computing gradient [here](https://github.com/rosinality/style-based-gan-pytorch/blob/master/train.py#L132)?
In the original implementation they don't do it. Look at [this line](https://github.com/NVlabs/stylegan/blob/master/training/loss.py#L163).

**Comment by rosinality** [comment]
Thank you, I will correct it.

**Comment by kobrien-Novetta** [comment]
I'm slightly confused on why this was closed. In the Commit, It looks like the softplus operation still occurs. Did you mean to do more than just change the variable name?
