### ISSUE TITLE
How to run code for distributive training on PyTorch?

### ISSUE THREAD

**Issue by obravo7** [rosinality/style-based-gan-pytorch#35]
Say I want to run this across two nodes each with 8 GPUS, do I only have to adjust the train.py file or the whole model?

**Comment by rosinality** [comment]
PyTorch document says DistributedDataParallel https://pytorch.org/docs/stable/nn.html#distributeddataparallel not works with torch.autograd.grad(), so maybe you can't run this code in distributed settings.
