### ISSUE TITLE
Wrong file permissions

### ISSUE THREAD

**Issue by MichaelMonashev** [rosinality/style-based-gan-pytorch#43]
These files have execution bits, but should not be.
```
-rwxrwxr-x generate.py
-rwxrwxr-x model.py
-rwxrwxr-x README.md
-rwxrwxr-x train.py
```
how to fix it:
```
git update-index --chmod=-x generate.py model.py README.md train.py
git commit -m "Changing file permissions" generate.py model.py README.md train.py
git push
```

Sorry, Github does not have a web interface to make the pull request with file permissions. So, I write this issue.

**Comment by rosinality** [comment]
Update file permissions in 17af890fcb8858357ef7a1f8a6d1dcdefbdab5dc. Thank you!
