### ISSUE TITLE
generate 256px img using pretrained model get wired picture

### ISSUE THREAD

**Issue by rentonliu** [rosinality/style-based-gan-pytorch#49]
Hi Seonghyeon,
Thank your so much for your efforts.
I used your pretrained 256px model to generate images by simply running:
```bash
python generate.py 'checkpoint/pretrained/stylegan-256px-new.model'
```
here is what i got:

![image](https://user-images.githubusercontent.com/4425798/64522663-14f37780-d32d-11e9-9716-9f23ab1b17de.png)

Could you plz point out what am I doing wrong here

Thank you

**Comment by MichaelMonashev** [comment]
Try to convert from BGR to RGB before saving.
```
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) 
```

**Comment by SheldonTsui** [comment]
@rentonliu you didn't set the size properly.
parser.add_argument('--size', type=int, default=1024, help='size of the image')

**Comment by rentonliu** [comment]
Thank you!
