### ISSUE TITLE
ConvBlock in Discriminator

### ISSUE THREAD

**Issue by omrysendik** [rosinality/style-based-gan-pytorch#57]
Hi,

Is line 520 in model.py deliberate? Notice the input size is 513 (and not 512 ?)
ConvBlock(**513**, 512, 3, 1, 4, 0),

Thanks for the clarification

**Comment by rosinality** [comment]
Mean of batch standard deviation of feature maps is concatenated to conv feature maps (to increase sample variations). So input channel become 512 + 1.

**Comment by omrysendik** [comment]
Yup, I just realized my mistake.
Sorry for the fuss and thanks for the clarification!
