### ISSUE TITLE
Generated images color issue

### ISSUE THREAD

**Issue by shubhamn21** [rosinality/style-based-gan-pytorch#58]
The output generated images are inverted/rendering with the wrong palette of colors. Could you please check what is wrong here?

**Comment by shubhamn21** [comment]
https://drive.google.com/file/d/1NIGq8ehgpPjcuzWNhPJYngHBcVfzpSAU

**Comment by rosinality** [comment]
Did you set --size argument correctly? If it is not image is colored using previous/next to_rgb convs, so color will be incorrect.

**Comment by shubhamn21** [comment]
Hey @rosinality,
that did it! 
Thanks :)
