### ISSUE TITLE
how to train on own dataset

### ISSUE THREAD

**Issue by Johnson-yue** [rosinality/style-based-gan-pytorch#6]
it's me again, if I want to train my own dataset  , how to do this.
your code support CelebA  dataset by **datasets.ImageFolder**  of pytorch API.
If my dataset format is the same as **datasets.ImageFolder**  api. like:

> root/class1/xxx.jpg
> root/class1/yy.jpg
> root/class1/zz.jpg
>
> root/class2/xxx.jpg
> root/class2/yy.jpg
> root/class2/zz.jpg

Can I train the code?? and you already support multi-GPU ,is it?

**Comment by rosinality** [comment]
You can do that same as using celeba dataset. It uses ImageFolder so it supports ImageFolder style data arrangements.

Currently trainer supports DataParallel. So you could do multi gpu training.

**Comment by Johnson-yue** [comment]
But, I have one question!
how do I specify a generated category, I think you did not use the *label* variable.
In style-GAN,  the style is from z (or w), but z is also a noise of normal distribution.

like you _sample_mixing.png_  , I usually do not know how to generator _sample_mixing.png_

**Comment by rosinality** [comment]
I think you can use label informations by using approaches similar to Big GANs. (conditional normalizations and projection discriminator.)

In Style GANs authors used additional classifiers to classify attributes in the latent spaces. I simply randomly sampled samples.

**Comment by Johnson-yue** [comment]
Hi, I run you code with my dataset ,pytorch version is 0.4.1, and got this error
![image](https://user-images.githubusercontent.com/10268274/53145843-d12d6080-35dc-11e9-9c3e-dcd253926c02.png)
the important message is:
> RuntimeError: invalid gradient at index 0 - excepted shape [] but got [1]
and the first line and second line show my trace,
**real_predict** have a correctly value,  but **mone** is error shape.
So is this a bug ?? or my dataset have some trouble?

**Comment by rosinality** [comment]
Seems like that scalar tensor related problem. Mabe you can try mone = tensor(-1) or pytorch 1.0

**Comment by Johnson-yue** [comment]
I fixed it with 
> mone = torch.mean(mone)

thank you
