### ISSUE TITLE
Continue train

### ISSUE THREAD

**Issue by voa18105** [rosinality/style-based-gan-pytorch#7]
Is there a simple way to continue train? Is it possible without saving/loading discriminator state?

**Comment by rosinality** [comment]
I haven't tried it, maybe you can freeze generator and train discriminator few iterations, then unfreeze generator.

**Comment by voa18105** [comment]
Thanks

**Comment by ParthaEth** [comment]
Hi, I wanted to know if this worked? Can you actually freeze the generator to train the discriminator?
