### ISSUE TITLE
Slow training on multiple GPUs

### ISSUE THREAD

**Issue by albusdemens** [rosinality/style-based-gan-pytorch#78]
When I use multiple GPUs instead of one, the training time reduces by 80% (see below). Is there a way to fix this?

The issue has previously been [reported (and fixed)](https://github.com/rosinality/style-based-gan-pytorch/issues/44), but changing `num_workers` doesn't fix the issue. 

Training times:
One GPU: 10.71 it/s
Four GPUs: 1.13 it/s

```
CUDA_VISIBLE_DEVICES=4 python train.py --mixing --loss wgan-gp ./Maps_512px_high/
Size: 8; G: 29.625; D: -16.795; Grad: 1.407; Alpha: 1.00000:   0%| | 132/3000000 [00:12<77:49:10, 10.71it]
CUDA_VISIBLE_DEVICES=4 python train.py --mixing --loss wgan-gp ./Maps_512px_high/
Size: 8; G: 29.625; D: -16.795; Grad: 1.407; Alpha: 1.00000:   0%| | 132/3000000 [00:12<77:49:10, 10.71it]
```

**Comment by rosinality** [comment]
This implementation is not very efficient in multi gpu settings, but I don't know why slowdown occurs. Maybe at resolution 8 model is quite small, so communication cost dominates training. Could you test at a larger resolutions?

**Comment by albusdemens** [comment]
OK. By the way, congratulations for your work - it's very well done! 

I benchmarked the speed starting at different resolutions and this is what I got:

- `init_size`=16 --> 1 GPU = 6it/s, 4 GPUs = 1.4 it/s 
- `init_size`=32 --> 1 GPU = 2 it/s, 4 GPUs = 1.5 it/s
- `init_size` = 64 --> 1 GPU = 1.4 it/s, 4 GPUs = 1.75 it/s

So it looks like using multiple GPUs is convenient only when starting from a large size, which on the other hand goes against the StyleGAN philosophy, if I understood correctly (this might prevent the formation of nice large-scale features). Another solution could be to reduce the batch size. I'll try that as soon as I have time.

**Comment by rosinality** [comment]
Hmm I will look at it. By the way, I recommend StyleGAN 2 if you don't need progressive training.

**Comment by albusdemens** [comment]
Thanks. Yes I plan to give a try to StyleGAN2 too (I still need to properly study the paper, ops). Another thing: where do you define which latent vector(s) to use?

**Comment by rosinality** [comment]
You can set mixing_range to specify the range of layers that will use the second latent vector.

**Comment by albusdemens** [comment]
All clear. Is the first latent vector explicitly defined somewhere in the
code?

**Comment by rosinality** [comment]
StyledGenerator can take list of vectors, so you can pass list of noises.
