### ISSUE TITLE
How to use the discriminator alone to output a score for the authenticity of an image？

### ISSUE THREAD

**Issue by MeowTsukiko** [rosinality/style-based-gan-pytorch#79]
We want to judge whether the image is real or fake. So we trained a model and used its discriminator to output a score. 

`discriminator = nn.DataParallel(Discriminator(from_rgb_activate=not args.no_from_rgb_activate)).cuda()`
`discriminator.module.load_state_dict(torch.load('./checkpoint/train_step-7.model')['discriminator'])`
`score = discriminator(x0,step=6,alpha=alpha)`

Can we use the discriminator as above?

And we don't understand the parameters 'alpha' and 'step' in the discriminator. And we can't restore the model saved in the training.

We are looking forward to your reply. Thanks a lot.

**Comment by rosinality** [comment]
alpha is weights for fading steps after resolution changes. step is resolution of generator/discriminator is training. If you use train_step-7.model checkpoints, alpha will be 1.0 and step will be 7. You can load discriminator weights as you wrote. If there are errors, please post logs.

But I don't know discriminator score is reliable measures for judge image is real or fake.

**Comment by MeowTsukiko** [comment]
Thank you for your reply. I wondering if the 'step' is related to the size of the input images. We used 256×256 pictures to test, and no matter which model ( train_step-7, train_step-6, train_step-5...)we chose, the 'step' can only be set to 6. If we set it to 7 or other numbers, there will occur this wrong:

> File "/home/customer/Dong_project/jupyter/GAN/rosinalitynstyle-based-gan-pytorch-master/Discriminate.py", line 150, in <module>
>  score = discriminator(x0,step=7,alpha=1.0)
> File "/home/customer/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
> result = self.forward(*input, **kwargs)
> File "/home/customer/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
> return self.module(*inputs[0], **kwargs[0])
> File "/home/customer/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
>   result = self.forward(*input, **kwargs)
> File "/home/customer/Dong_project/jupyter/GAN/rosinalitynstyle-based-gan-pytorch-master/model.py", line 562, in forward
> out= torch.cat([out, mean_std], 1)

> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 4 and 2 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71

We are looking forward to your reply, thanks a lot.

**Comment by rosinality** [comment]
You should use 512x512 images for step 7.

**Comment by MeowTsukiko** [comment]
The output of the StyleGAN discriminator does not use the sigmoid, so it is impossible to score the image between 0 to 1. We tried DCGAN, but it has poor performance. We would like to ask if you have ever seen which kind of GAN with discriminator output used sigmoid and perform better.

Or if we replace the loss function of StyleGAN with the loss function of the original GAN, will it work?

**Comment by rosinality** [comment]
StyleGAN with R1 penalty uses standard gan loss, so it is equivalent to using sigmoid activation with cross entropy. But I think you may need to do some calibrations to get more meaningful scores.

**Comment by MeowTsukiko** [comment]
Thanks a lot  ^_^
