### ISSUE TITLE
Strange curve when plotting pixel size as a function of iteration number

### ISSUE THREAD

**Issue by albusdemens** [rosinality/style-based-gan-pytorch#80]
Using TensorBoard, I plot the size of the generated image as a function of the iteration number (see [this](https://gist.github.com/albusdemens/749b02cb184c06198d3b6a46dba4abe5#file-train-py-L281) modified version of train.py).

In the plot, some of the transitions between resolutions have a zig-zag pattern, instead of a step one. Is this because of a bug somewhere? Also, why do some transitions exhibit the expected step pattern while others don't?

![image](https://user-images.githubusercontent.com/276459/73258710-95285580-41c6-11ea-8fe0-f64a1dbab53e.png)

**Comment by rosinality** [comment]
I think the reason is batch size is changed when resolution changed. That is, `i * args.batch.get(step)` is not monotonic.

**Comment by albusdemens** [comment]
Thanks! that was easy ;-)
