### ISSUE TITLE
affine transformation seems missing

### ISSUE THREAD

**Issue by xiangyu1991** [rosinality/style-based-gan-pytorch#82]
Hi,
I am really appreciate your  more readable codes. But in you code, it seems that you directly put the style W(which is produced by Mapping network from Z) to StyledConvBlock without any affine transformation. Am I right?

**Comment by rosinality** [comment]
Affine transform is in here: https://github.com/rosinality/style-based-gan-pytorch/blob/master/model.py#L278

**Comment by xiangyu1991** [comment]
thanks
