### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xb8'.

### ISSUE THREAD

**Issue by yunfei-shi** [rosinality/style-based-gan-pytorch#9]
Hi, I use the pre-trained model but get the following error, my pytorch version=1.0.0, can any one help me?
python generate.py 
Traceback (most recent call last):
  File "generate.py", line 7, in <module>
    generator.load_state_dict(torch.load('./checkpoint/style-gan-600k.model'))
  File "/home/ubuntu/miniconda3/envs/dl/lib/python3.6/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/ubuntu/miniconda3/envs/dl/lib/python3.6/site-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '\xb8'.

**Comment by rosinality** [comment]
Hard to guess why...maybe pickle file is damaged. Could you recheck checkpoint files?

**Comment by yunfei-shi** [comment]
The file is about 100MB, is that right?

**Comment by rosinality** [comment]
Yes, and sha1sum is f177120fd57460288c276da5636b6685a139024c.

**Comment by nile649** [comment]
pickle file requires, env to be very same as the author who provides pretrained model. 
torch==1.0.1
python==3.6

**Comment by yunfei-shi** [comment]
I download the file again and check the sha1sum, it works now, I think the file is damaged, thinks!
